-- =====================================
-- 飲料訂購系統：Supabase SQL
-- 請到 Supabase > SQL Editor 執行
-- =====================================

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.stores(id) on delete cascade,
  name text not null,
  price integer not null check (price >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.toppings (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.stores(id) on delete cascade,
  name text not null,
  price integer not null default 0 check (price >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  store_id bigint references public.stores(id),
  product_id bigint references public.products(id),
  product_name text not null,
  sugar text not null,
  ice text not null,
  topping_name text,
  quantity integer not null default 1 check (quantity > 0),
  unit_price integer not null check (unit_price >= 0),
  total_price integer not null check (total_price >= 0),
  note text,
  created_at timestamptz not null default now()
);

-- 啟用 RLS
alter table public.stores enable row level security;
alter table public.products enable row level security;
alter table public.toppings enable row level security;
alter table public.orders enable row level security;

-- 第一版示範：任何拿到 anon key 的人都可以讀菜單、送訂單、看訂單
-- 公司內部測試可先這樣；正式上線建議再加登入與管理員權限。

drop policy if exists "stores_read_all" on public.stores;
create policy "stores_read_all"
on public.stores for select
using (true);

drop policy if exists "products_read_all" on public.products;
create policy "products_read_all"
on public.products for select
using (true);

drop policy if exists "toppings_read_all" on public.toppings;
create policy "toppings_read_all"
on public.toppings for select
using (true);

drop policy if exists "orders_insert_all" on public.orders;
create policy "orders_insert_all"
on public.orders for insert
with check (true);

drop policy if exists "orders_read_all" on public.orders;
create policy "orders_read_all"
on public.orders for select
using (true);

-- =====================================
-- 測試資料
-- =====================================

insert into public.stores (name)
select '測試飲料店'
where not exists (
  select 1 from public.stores where name = '測試飲料店'
);

insert into public.products (store_id, name, price)
select s.id, v.name, v.price
from public.stores s
cross join (
  values
    ('熟成紅茶', 35),
    ('春芽冷露', 35),
    ('白玉歐蕾', 60),
    ('胭脂多多', 50)
) as v(name, price)
where s.name = '測試飲料店'
and not exists (
  select 1 from public.products p
  where p.store_id = s.id and p.name = v.name
);

insert into public.toppings (store_id, name, price)
select s.id, v.name, v.price
from public.stores s
cross join (
  values
    ('白玉', 10),
    ('珍珠', 10),
    ('椰果', 10)
) as v(name, price)
where s.name = '測試飲料店'
and not exists (
  select 1 from public.toppings t
  where t.store_id = s.id and t.name = v.name
);
